### ISSUE TITLE
(1.20.1) Crash on world generation or startup - Error with Embedium Sky Cloud Edge Renderer

### ISSUE THREAD

**Issue by matrixfury** [baileyholl/Ars-Nouveau#1302]
Error is as the title says, using the newest versions of both Ars Nouveau and Embedium.

[crash-2024-05-16_11.59.35-client.txt](https://github.com/baileyholl/Ars-Nouveau/files/15343262/crash-2024-05-16_11.59.35-client.txt)

**Comment by matrixfury** [comment]
If anyone can help with this, it would be much appreciated

**Comment by embeddedt** [comment]
This is probably caused by using the `Conquest_1.20.zip` resource pack, which includes a clouds texture that is incompatible with Sodium's faster cloud renderer. Embeddium will fix this in the next release; in the meantime disabling clouds in Video Settings before joining a world should work around the issue, or you can just not use the resource pack.

(In other words, this is probably not Ars Nouveau's bug.)
