### ISSUE TITLE
[1.20.1] Crash gateways loot 

### ISSUE THREAD

**Issue by jinkhya** [baileyholl/Ars-Nouveau#1312]
Hello,
A player is playing on our atm9 to the sky server and it crashed when he used a gateway.
Here's the crash log : https://gist.github.com/jinkhya/943fd7314719e5989cf54eb2d7d73338

I reported it to Gateways' dev first but they said it seemed to be on Ars Nouveau's side, so here I am :)

Thanks in advance,
Jin

**Comment by evhub** [comment]
Getting a similar issue: https://gist.github.com/evhub/98fa94b2aaa4b072680ffba9845c355a (also worth noting this looks like the same issue as in #1308)

**Comment by jeremiahwinsley** [comment]
It looks like this is due to the blacklist logic being inverted:

https://github.com/baileyholl/Ars-Nouveau/blob/836d001483f0bb3313dfcebd82c867bcc236e659/src/main/java/com/hollingsworth/arsnouveau/api/loot/DungeonLootTables.java#L65

This only allows items that are on the blacklist, resulting in a list size of 0, which is an invalid upper bound. There should probably be a bounds check here too, in case someone does want to blacklist all tablets.

**Comment by baileyholl** [comment]
Fixed in latest commit
