### ISSUE TITLE
EMI support 

### ISSUE THREAD

**Issue by whatthedrunk** [baileyholl/Ars-Nouveau#1344]
I would like to add the mod to ATM10 but it requires JEI and right now JEI and EMI running side by side isn't the best option. Would it be possible to not require JEI?

**Comment by baileyholl** [comment]
Hello,
Are those issues still occurring? My understanding is that the initial issues with both have been fixed now. 

JEI is required until Patchouli is ported, otherwise the custom recipes would be totally missing from the game, and fairly unplayable. The requirement will be removed when patchouli is available and I am able to reenable the guide book.

**Comment by whatthedrunk** [comment]
Right now it's possible for both to load but when you first load it up it takes a very long time to show in game and I can only assume it's gonna get worse once the pack gets larger. We can wait till patchouli is updated or wait until they both load quicker together.

**Comment by whatthedrunk** [comment]
I just tested the newest JEI with EMI on the newest Neoforge and it loaded a lot faster than before so I was able to add it. Having support for EMI or JEI should be an option but ill close this issue for now and reopen if things get bad again. Thanks!

**Comment by TheUnKnownLink-URS** [comment]
I would like to see this made compatible with emi as well because JEI just isnt as good as emi for loading words due to EMI loading recipes while youre in the world while JEI makes you wait which for modpacks that have lots of recipes it just takes forever
