### ISSUE TITLE
SpellBookRenderer [Crash Report][Mod loading error]

### ISSUE THREAD

**Issue by KnightJimmy91** [baileyholl/Ars-Nouveau#189]
[crash-2021-03-03_02.25.02-fml.txt](https://github.com/baileyholl/Ars-Nouveau/files/6074290/crash-2021-03-03_02.25.02-fml.txt)

**Comment by pja1982** [comment]
I had crash with GeckoLib 1.16.5-3.0.15
Rolled back to 1.16.5-3.0.14

**Comment by Admiral-Sebastian** [comment]
This issue is related to GeckoLib 1.16.5-3.0.15
I reprogrammed function that Ars-Nouveau can't process
Rollback to 1.16.5-3.0.14 of GeckoLib to work with the current version of Ars

**Comment by Winddbourne** [comment]
I encountered this too and did the roll back, but remember that's a temporary fix to keep things working in the short term.  In the long run . . . 

You have to remember not to update Gecko every day when you are updating mods in your pack

If other mods that depend on Gecko updates to REQUIRE the new version your screwed, and Gecko has 43 PAGES worth of dependents. 

Rolling back is the short term fix, in the long run sending the crash report and having the mod authors handle it is the long term fix. Handling it could mean they stop depending on gecko, pester gecko's mod author to make a fix, or change their mod to be compatible with the new function. 

But that's it. Definitely gotta make people aware of the problem here though. Nobody can do anything until they are aware of the problem. LOL

**Comment by Winddbourne** [comment]
And this morning it's fixed. Good job! :)

**Comment by baileyholl** [comment]
Fixed in the latest version.
