### ISSUE TITLE
Ars Nouveau spawns Wilden mobs in the ATM6 Mining Dimension

### ISSUE THREAD

**Issue by tanyan-tanyan** [baileyholl/Ars-Nouveau#207]
Hi, there is an issue on the mod's end according to an ATM6 Dev, where the new Wilden mobs spawn in the Mining Dimension from ATM6, despite the dimension disabling mob spawn entirely. Not only do they spawn where they shouldn't spawn, they spawn uncontrollably underground if given enough space.

![Discord_gg9FJaJZTQ](https://user-images.githubusercontent.com/68793071/113587749-2430c900-9627-11eb-9125-35a5198744d8.png)

![java_R64xBKzEhl](https://user-images.githubusercontent.com/68793071/113587789-327ee500-9627-11eb-9910-9df3b672d3e3.png)

![java_TfuDM6Wtg2](https://user-images.githubusercontent.com/68793071/113587854-4aeeff80-9627-11eb-96ca-5ee44ed887af.png)

**Comment by Gbergz** [comment]
This still happens even on the newest version that claims to have fixed it.

This: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3264874

**Comment by baileyholl** [comment]
Did you make sure to kill all of the entities in the area? They would not despawn from this update.

**Comment by Gbergz** [comment]
This is on a fresh world. They are spawning all around.

**Comment by c0nnex** [comment]
I can confrim this issue with that mod version. (ars_nouveau-1.16.4-1.12.5.jar)
Advanced mining dimensions with disabled mobs affected. We consider removing ars Nouveau from our pack (modded DW20), as it makes the  mining dimension useless, cause players die to elite wilders all the time.

**Comment by thevortex** [comment]
ATM6 Mining dimension, ars_nouveau-1.16.4-1.12.5.jar, freshly generated world as of today (ATM6 1.5.10b), can confirm after 1 hr in game in survival mode in a large cavern that no mobs have spawned in yet and the data that is creating this dimension has not changed since well before this issue began

**Comment by DiegoBranco** [comment]
Can confirm that issue persists in 1.13.0. 

Would like to add that since adding this mobs to the game, this also happens in The Undergarden (tested in 0.4.2) and The Twilight Forest (tested in 4.0.412). 

Thankfully it does not drown the spawns from these mods, but an option to limit Wilden spawns to the overworld would be appreciated.

**Comment by baileyholl** [comment]
Mods that use vanilla biome categories in their dimension are going to get other modded spawns. This is entirely the purpose of the forge biome loading events. If these mods are not supposed to have any mobs at all, then they need to explicitly handle that themselves, or use a different biome type. 

I will add config options to blacklist certain dimensions, but truthfully these mods are supposed to handle this themselves if modded spawns are unintended in their biome.

**Comment by thevortex** [comment]
The way that datapack biomes and dimensions work is via static json files
and any mobs or lack of mobs is hard coded in the file, but also, the atm
mining dim is its own category, not overworld

**Comment by baileyholl** [comment]
The latest version now has a dimension blacklist: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3278608
