### ISSUE TITLE
mana not regenerating | 1.16.5 multiplayer

### ISSUE THREAD

**Issue by wehehehehehehehehehehe** [baileyholl/Ars-Nouveau#345]
After getting my first familiar (a sylph) I noticed my mana was not regenerating.
I tried dying and changing book but it did not regenerate.
I can use a Caster Tome infinitely now.

WildSMP modpack latest version

**Comment by baileyholl** [comment]
Please use the latest version, this is a bug with familiars on servers. https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3445939

**Comment by Dempat1** [comment]
I don't know if this it's necroposting (Tell me and I will delete it, sorry if it is). But I have the same problem as him, but the differences are that I'm playing at 1.16.5 last version, and it tells me that I cannot throw any spells because I don't have mana. 



(This part it's not important)
There was a whole bug with other add-ons of the mod (ars combat fight if I remember) that mod puts a spell that it's called "Stalwart". That spell it's bugged, almost in servers, yesterday a friend shot another with that, and the shooted friend player corrupted his data files. (this it's like the USA, but combined with Hogwarts). After that the player was immortal, like not die with nothing, /kill, void, /ban, nothing, and he can grab nothing. I mean, that's not a problem principally of ars nouveau, but it's funny, I think.  

My question it's: there it's a way a restart with command your mana? I mean, like put /ars_nouveau restart mana (player), or something similar?  (please skip all after the second bug, it's not important at all)
