### ISSUE TITLE
[1.18.1] Timer spell turret doesn't cast touch -> redstone signal

### ISSUE THREAD

**Issue by tomko157** [baileyholl/Ars-Nouveau#457]
https://user-images.githubusercontent.com/32019796/153493358-38a5e902-f01b-4825-b6e8-b5c1011b3808.mp4

The block accepts the spell when cast through a book, but not through the turret. Even if the turret faces other faces of the block, it still doesn't cast the signal.

Version 2.2.2

**Comment by baileyholl** [comment]
Redstone Signal is a bit hacky an unintuitive at the moment. Since redstone works entirely based on blocks being placed, Redstone Signal creates a fake block of air that gives off a redstone signal. Because of this, casting the turret directly into the block will not place it.

Instead, destroy that cobblestone 1 below the turret, and it should work.
