### ISSUE TITLE
Possible ticking loop caused by ars Nouveau

### ISSUE THREAD

**Issue by Papaturts** [baileyholl/Ars-Nouveau#462]
Unsure if its this mod causing it-its mentioned in several of the crashes
would like some possible thoughts or possibly pointed in the right direction would be greatly appreciate
Thank you
[crash-2022-02-13_16.26.20-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/8056309/crash-2022-02-13_16.26.20-server.txt)
d

**Comment by baileyholl** [comment]
This is the Minecraft watchdog killing the server early, you need to set max-tick-time to -1 in the server.properties. 

This can happen when the server is lagging, for whatever reason, but unrelated to this mod from this log alone.

**Comment by Papaturts** [comment]
Alrighty, thank you
Could a few more logs help or not really as they seem to be watchdog
related as well?

**Comment by baileyholl** [comment]
If you are experiencing issues with tick time, consider running a Spark profile and see if anything unusual stands out, but that log you have posted is purely because a single tick took too long. Change that server.properties setting and keep investigating if needed. https://www.curseforge.com/minecraft/mc-mods/spark
