### ISSUE TITLE
[Bug 1.18.2] Sourceberry is not tagged as a fruit

### ISSUE THREAD

**Issue by Peach774** [baileyholl/Ars-Nouveau#513]
Sourceberry is not tagged as a fruit and so it doesnt get recognized by other mods as fruit.

**Comment by Alexthw46** [comment]
Which mods are you talking about exactly? I don't see a fruit tag included in forge, so we'd need to know which one they are using, assuming it's a shared one.

**Comment by Peach774** [comment]
Most crop mods and diet use forge:fruits/fruitname. You can check croptopia, harvestcraft or diet for examples.

**Comment by Alexthw46** [comment]
Ok, i checked. That's true for harvestcraft, while diet use another one and they included many fruits from another mods themselves, croptopia uses yet another tag that seems to belong to another mod (why so many different tags <.<).
I've added it to forge:fruits/berry to my open PR #522 so it should work for few ones.
Consider opening an issue in Diet to make them add the berry, since they seem to accept that kind of requests.
