### ISSUE TITLE
Bamboo and Sugar Cane growth doesn't generate World Mana?

### ISSUE THREAD

**Issue by Dragnier** [baileyholl/Ars-Nouveau#57]
I've been trying to see if bamboo and sugar cane generate world mana when near the condenser and they don't seem to. Is this intentional or a bug? I haven't checked kelp yet but since it works on a similar mechanic, I would guess it doesn't either?

**Comment by DerringersMods** [comment]
If I read it right, sugar cane in particular appears to be bugged in Forge because it generates a pre-growth event but no post-growth event. [Apotheosis reimplements sugar cane](https://github.com/Shadows-of-Fire/Apotheosis/blob/1e23659571aa910e38fe64967c884b15aec9d972/src/main/java/shadows/apotheosis/garden/ApothSugarcaneBlock.java#L47) with the correct events, but it's a mixed-bag-of features mod you may not want.

Bamboo generates the correct post-growth event, but in a twist of irony Apotheosis removes it, so you'd be trading one bug for another.

Kelp, nether vines, cacti and chorus trees should all produce the necessary events to trigger mana generation.

Once any plant reaches its maximum growth potential it can no longer grow and therefore no longer produces mana.

**Comment by Dragnier** [comment]
I was using Apotheosis already and Sugar Cane was not producing; but neither was Bamboo so I suppose something else was changing it too maybe? I'll have to do some more testing to see I guess and report back.

**Comment by DerringersMods** [comment]
Only the growing tip of Apoth sugar cane produces, so if it's already very tall it may have grown out of range of your condenser.

**Comment by Dragnier** [comment]
It was not tall yet, but for future reference: how high from the condenser does the range go?
