### ISSUE TITLE
Dupe bug with sophisticated storage

### ISSUE THREAD

**Issue by Jester9000** [baileyholl/Ars-Nouveau#702]
when using the break spell on a sophisticated storage chest that has been wrapped with sophisticated storage packing tape the chest is destroyed dropping all contents but the packing tape still functions (keeping the contents of the chest)

**Comment by LavaCatPlayz** [comment]
Something to note is that if a projectile form is used instead of just letting all the objects out onto the ground what will happen instead is the chest itself is duplicated but also the original chest gets bugged where it is packing taped but it isn't and you can open it (Visual packing tape bug unsure what happens to it if you relog). This version of the dupe adds on the duping off the chest and the lessening of lag due to dropping 80k deepslate onto the ground in an ATM 7 official public server... I wish I knew this variant when abusing it before I left the ATM server. Sorry for the bad video but it was filmed quickly to show a friend how cursed the packing tape visual bug is.

https://user-images.githubusercontent.com/69319607/194441448-6a289d04-8e49-42ae-b541-6afd68acda46.mp4

**Comment by baileyholl** [comment]
Fixed next version
