### ISSUE TITLE
[Bug?] Casting empty or created spell results in additional mana

### ISSUE THREAD

**Issue by Tellik** [baileyholl/Ars-Nouveau#742]
When using a brand new spellbook, without any spells created in it, results in gaining additional mana. The message "Invalid Spell" appears, the mana bar gains a section of empty mana that then regenerates.

While using Ars Instrumentum to display numerically how much mana is available, I see 100/100 prior to this, and then I now have 150 maximum mana.

In some followup testing, I discovered that even using a created spell, such as projectile/harm will result in the same behavior, so I'm not even sure if this is a bug or intended behavior.

When using /ars-reset, the mana returns back to 100.

**Comment by Alexthw46** [comment]
Casting a Spell cause the max mana to update. 
Since one of the factors in determination of max mana is the tier of the book and the glyphs you know (6 starter glyphs), the base number gets updated with those bonus when you use the book for the first time



https://github.com/baileyholl/Ars-Nouveau/blob/ae93a46ce67bb70b592ad3b97a45f2d0141b8d9d/src/main/java/com/hollingsworth/arsnouveau/api/util/ManaUtil.java#L55

**Comment by Tellik** [comment]
Ah, got it. I wasn't sure if it was a bug or not since it also happened when there wasn't a valid spell being cast.
