### ISSUE TITLE
Bug - Enchantment not using Source from jars?

### ISSUE THREAD

**Issue by WishHeartStudios** [baileyholl/Ars-Nouveau#754]
For some reason when placing a source jar in the enchanting apparatus setup, the enchanter won't accept source from it and gives the "Recipe not found" message. I've tried looking everywhere for what might be causing this but I can't find anything.

**Comment by Alexthw46** [comment]
If it say "Recipe not found" the issue is not related to the source jar (unless you are placing it on the pedestals instead of simply placing it near the core, lol) but it's more likely a nearby pedestal that is interfering with the recipe matching.
When the recipe is correctly matched but it doesn't find a source jar it gives a more specific error
