### ISSUE TITLE
[1.19.2] Starbuncle, Drygmy, Whirlisprig, and trees do not spawn naturally on Terralith biomes

### ISSUE THREAD

**Issue by Ashendale** [baileyholl/Ars-Nouveau#780]
On MC 1.19.2, Ars Nouveau 3.5.1

None of the magical critters/trees spawn on any non-vanilla biome. I'm writting in hopes that on a future version the critters/trees are allowed to be black/white listed on biomes through the config files (as I think already happens by default with desert and cold biomes).

Maybe also dimension black/white list options, as well, since they don't show up on the Nether or End (as normally makes sense, but a pack could have them spawn there for whatever reason).

Thank you for reading, and for your work.

**Comment by Alexthw46** [comment]
Since 1.19.2 the mob spawns are jsons, thus datapack-able. If the biomes from terralith don't allow their spawns it can only mean they are not part of the "overworld" biome tag, something they need to fix. 
https://github.com/baileyholl/Ars-Nouveau/blob/1.19.x/src/main/resources/data/ars_nouveau/forge/biome_modifier/starbuncle_spawn.json
