### ISSUE TITLE
Mod stopped work with "shadowed" version of GeckoLib

### ISSUE THREAD

**Issue by uhloin** [baileyholl/Ars-Nouveau#784]
Since Forge upgraded from 43.1.57 to 43.1.58 there new crash-like bug appeared. The game on start after loading screen 100% with Mojang logo, switches to empty red screen and freezes. Or sometimes just quit. There is no crush log but stderr logs have exception which refers to GeckoLib and Ars Nouveau. Also presence of MCglTF library make some influence.

First I reported to owner of MCglTF. He said he could reproduce the same exception in logs with only GeckoLib in mods folder.
Second I reported to owner of GeckoLib. He said this is because Ars uses shadowed version. You can see dialog here: https://github.com/bernie-g/geckolib/issues/360

For me stable reproduction of "red screen" with this configuration:
MC 1.19.2 (not 19.3)
forge-1.19.2-43.1.58-installer.jar or forge-1.19.2-43.2.0-installer.jar
geckolib-forge-1.19-3.1.38.jar
ars_nouveau-1.19.2-3.5.1.jar
curios-forge-1.19.2-5.1.1.0.jar
Patchouli-1.19.2-77.jar
TerraBlender-forge-1.19.2-2.0.1.130.jar
MCglTF-1.19.2-Forge-2.0.0.0.jar

Exception log in the attachment.
[stderr.log](https://github.com/baileyholl/Ars-Nouveau/files/10201632/stderr.log)

**Comment by mattagray12** [comment]
having a very similar issue with lots of issues but no crash log. I also get these 

>TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:307) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:440) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:267) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:309) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:284) at
TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.molang.MolangParser.parseSymbolsMolang(MolangParser.java:205) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.molang.MolangParser.parseOneLine(MolangParser.java:194) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.molang.MolangParser.parseExpression(MolangParser.java:146) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.shadowed.eliotlash.molang.MolangParser.parseJson(MolangParser.java:115) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:178) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:55) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:172) at TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.geckolib3.util.json.JsonKeyFrameUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:279) at  TRANSFORMER/ars_nouveau@2.8.0/software.bernie.ars_nouveau.geckolib3.file.AnimationFileLoader.loadAllAnimations (AnimationFileLoader.java:33) at TRANSFORMER/ars_nouveau@2.8.0/software.bernies.ars_nouveau.geckolib3.resources.GeckoLibCache.Lambda$reload$0(GeckoLibCache.java:70)

not sure what seems to be the issue but I havent seen anything commented about this in a while and I physically cant play the game due to this

**Comment by baileyholl** [comment]
Should be fixed in latest 3.6.0

**Comment by uhloin** [comment]
Even before 3.6.0 game stop crushing on start but exception still is here (see attachment)
[latest_stderr.log](https://github.com/baileyholl/Ars-Nouveau/files/10317811/latest_stderr.log)

**Comment by baileyholl** [comment]
@uhloin Those logs are "normal" for geckolib. Unless you are crashing with a log related to this mod, there isn't much help I can give. If you experience another crash then please open a new ticket

**Comment by uhloin** [comment]
If the exception is not fatal it should be caught? At least to not spam the log. But I understood sometimes there are no place to catch.
