### ISSUE TITLE
Wixies are no longer able to craft custom potions

### ISSUE THREAD

**Issue by MuteTiefling** [baileyholl/Ars-Nouveau#852]
ars_nouveau-1.19.2-3.10.1
morejs-forge-1.19.2-0.0.7

I've been useing MoreJS to add different crafting recipes for potions. Previously, I was able to have a wixie craft these without issue. 

Now, however, it seems she doesn't recognize the items.

For example, she'll craft potions of leaping with the Rabbit's Foot and Wilden Wing, but not with the Crescent Fruit shown below. 
![image](https://user-images.githubusercontent.com/9543430/217407673-10f86b80-d323-4756-98f7-7e021c205ef5.png)

**Comment by LLytho** [comment]
Hey, MoreJS dev here.

From what I see it looks like you create own recipe wrappers when calling [addMix](https://github.com/baileyholl/Ars-Nouveau/blob/1.19.x/src/main/java/com/hollingsworth/arsnouveau/common/mixin/PotionRecipeMixin.java). In MoreJS I directly add the mix to the list instead of using `addMix`. The reason is to let users define custom ingredients with nbt checks etc. 

```js
MoreJSEvents.registerPotionBrewing((event) => {
    const ing = Ingredient.customNBT(/.*/, (nbt) => {
        return nbt.contains("Damage") && nbt.getInt("Damage") < 10;
    });
    event.addPotionBrewing(ing, "minecraft:fire_resistance", "minecraft:strength");
});
```
https://i.imgur.com/Y31eq6F.mp4

Currently I have two solution in mind.
1. Ars could probably mix into the `Mix` constructor. 
2. I use `addMix(Potion potion, Item item, Potion potion2)` instead of creating my own Mix object. But this will remove the ability to use custom ingredients, because of the way Mojang designed the method.

**Comment by baileyholl** [comment]
No worries, just some old cache code out of date. I think forge used to call addMix with their brewing registry, but I guess that changed or I imagined it.
