### ISSUE TITLE
[Request] Config to disable the Containment Spell capturing bosses

### ISSUE THREAD

**Issue by katubug** [baileyholl/Ars-Nouveau#932]
One of my players pointed out today that the Containment spell can capture the Ender Dragon, Wither, and all of the Twilight Forest bosses, and then use Drygmies to get their drops. This is a super cool feature, but it's very OP for my taste and I'd like the ability to disable it, please.

Thanks so much for your time, and for the absolutely phenomenal mod.

**Comment by Alexthw46** [comment]
Ender Dragon and wither won't drop anything from the jars, same for chimera, since the drop is spawned on death and not in the mob loot table. If you want to disable a mob from being jarred, you can add it to the entity type tag: `` [ars_nouveau:jar_blacklist](https://github.com/baileyholl/Ars-Nouveau/blob/1.19.x/src/generated/resources/data/ars_nouveau/tags/entity_types/jar_blacklist.json)``.

The #forge:bosses tag should hold all the bosses. Refer to vanilla datapack guides or stuff like KubeJs / CraftTw to add the mobs to the tag.

**Comment by katubug** [comment]
Thank you for the detailed response, I'll try the datapack thing. I appreciate your help!
