### ISSUE TITLE
Weird combo of interactions causing visual bug

### ISSUE THREAD

**Issue by Zethamnos** [baileyholl/Ars-Nouveau#962]
With shaders (Complimentary Reimagined) and putting mage armor (any) on armor stands, artifacts appear near the cursor that move when you move anywhere in the dimension of the armor stand (mainly when looking at sky). Upon further inspection and changing the armor around/moving, it turns out the visual glitch is actually the armor sprites of the armor on the stand.  You can especially see the hat around the cursor, lol. 

![2023-05-03_05 19 04](https://user-images.githubusercontent.com/120245024/236357056-9730b17e-f69d-463c-bd65-de5aeaf56d62.png)

**Comment by Alexthw46** [comment]
We're not sure yet from where this bug comes, could be a tri-mod combo bug or just the shaders and geckolib being weird.

Since you are one of the few with this bug, try this thing and report back if it solves, it would help narrowing down.

Disable the skyweave renderer in the client config - "Disables the skyweave renderer. Disable if your sky is broken with shaders." : "disable_skyweave" to true

**Comment by Zethamnos** [comment]
> We're not sure yet from where this bug comes, could be a tri-mod combo bug or just the shaders and geckolib being weird.
> 
> Since you are one of the few with this bug, try this thing and report back if it solves, it would help narrowing down.
> 
> Disable the skyweave renderer in the client config - "Disables the skyweave renderer. Disable if your sky is broken with shaders." : "disable_skyweave" to true

I tried with the mentioned change, and it looks to have removed the sprites for everything except the hats. I have now noticed that if you move far enough away, the sprite glitch goes away, when before it would follow the entire overworld. It also goes away if it is no longer outside, or I move inside (So no direct/indirect line of site). Mostly fixed, and now even more niche! thanks!

**Comment by Alexthw46** [comment]
While we are not sure why there's a difference between with and without skyweave,

The issue relies inside entity shadow rendering, imagine it as if Oculus render a player far away to calc its shadow shape etc but that player is not invisible for some reason. Disable Entity Shadows in your shader to remove the bug until it's fixed by Oculus or Geckolib, or they yell back at us etc.

**Comment by Zethamnos** [comment]
Ok, thanks!
