### ISSUE TITLE
CTD from dynamic light feature

### ISSUE THREAD

**Issue by Hiranus** [baileyholl/Ars-Nouveau#988]
MC 1.19.2
Forge 43.2.11
Ars Nouveau 3.13.4
I also use Rubidium and Oculus with BSL shaders.
I have many other mods but it doesn't seem that they are important here.

Java just died on me with EXCEPTION_ACCESS_VIOLATION. It seems that offender is
```
# Problematic frame:
# J 76583 c2 com.hollingsworth.arsnouveau.common.light.LightManager.getDynamicLightLevel(Lnet/minecraft/core/BlockPos;)D ars_nouveau@3.13.4 (69 bytes) @ 0x000002040bb3b2ee [0x000002040bb3b0a0+0x000000000000024e]
```

Log:
https://paste.ee/p/YdGmL
Report file mentioned in the log that has more details
[hs_err_pid18824.log](https://github.com/baileyholl/Ars-Nouveau/files/11539797/hs_err_pid18824.log)

**Comment by baileyholl** [comment]
Wish I could be more help, but memory errors are notoriously hard to debug - especially something that can't be reproduced reliably. There was a memory leak with skyweave that has been fixed and could have contributed, otherwise I would disable dynamic lights and see if you are still being impacted. Shaders can always cause shenanigans, especially with something as hacky as dynamic lights
